### ISSUE TITLE
Implement vt's style guidelines

### ISSUE THREAD

**Issue by cwschilly** [DARMA-tasking/vt-tv#105]
As mentioned in [this comment](https://github.com/DARMA-tasking/vt-tv/pull/85#pullrequestreview-2228799544) by @nlslatt

**Comment by tlamonthezie** [comment]
Hello @cwschilly it seems that the script generating the header in .h and .cc files has already been integrated in #85 
Is there anything else related to guidelines in the current issue ?

**Comment by cwschilly** [comment]
Hi @tlamonthezie 

Yes the license issue should be resolved. The remaining work on this issue is to go through the vt-tv code and make sure that all style guidelines from vt are being followed.

For reference:
- vt's [style guidelines](https://github.com/DARMA-tasking/vt/blob/develop/style-guidelines.txt)
- vt's [Doxygen style guidelines](https://github.com/DARMA-tasking/vt/wiki/Doxygen-Style-Guidelines)
- vt's [`.clang_format`](https://github.com/DARMA-tasking/vt/blob/develop/.clang-format) file

**Comment by tlamonthezie** [comment]
Checks for vt's [style guidelines](https://github.com/DARMA-tasking/vt/blob/develop/style-guidelines.txt):
(in `src` and `tests` directories)

- [x] Do not use "typedef", always use "using"

**Comment by tlamonthezie** [comment]
@cwschilly @lifflander  I noticed that in the header the licence contains the line "// Copyright 2019-2024 National Technology & Engineering Solutions of Sandia, LLC" which is **81** characters length. This is not compliant with the 80 char max per line guideline.
Should we break that line before "LLC" ?

**Comment by cwschilly** [comment]
@tlamonthezie We probably want to stick with whatever vt is using--even if it goes past 80 char
