### ISSUE TITLE
Generate visualization in vt-tv from Python bindings

### ISSUE THREAD

**Issue by pierrepebay** [DARMA-tasking/vt-tv#16]
Use nanobind.

The goal is to have on the Python side:
`import vttv`
`viz = vttv.Visualizer([some parameters])`
`viz.generate("filename.png")`

**Comment by pierrepebay** [comment]
After discussion, the goal is to allow vt-tv to replace the visualization backend of `LBAF`. To do this, we will start with a JSON interface between `LBAF` and a Python binded `vt-tv` api. The JSON data should not be written to disk, but kept in memory and exchanged as is.

**Comment by ppebay** [comment]
This is related to [https://github.com/DARMA-tasking/LB-analysis-framework/issues/410](https://github.com/DARMA-tasking/LB-analysis-framework/issues/410)

**Comment by pierrepebay** [comment]
To complete this work, all LBAF supported QOIs need to be supported by vt-tv. They will  be listed here: #44
