### ISSUE TITLE
Get rendering pipeline to obtain similar output to LBAF

### ISSUE THREAD

**Issue by pierrepebay** [DARMA-tasking/vt-tv#17]
This includes scalar bars, rank coloring, line coloring.

**Comment by stmcgovern** [comment]
@pierrepebay you are correct - please put the comparison pngs here. This issue can be left open so that the convergence can be worked upon later. Thanks!

**Comment by pierrepebay** [comment]
| Current vt-tv png output | Current LBAF png output |
| - | - |
|<img src="https://github.com/DARMA-tasking/vt-tv/assets/68857547/4aab7697-5ab2-4246-a167-1936e50761e2">|<img src="https://github.com/DARMA-tasking/vt-tv/assets/68857547/e4469f78-7213-4c0e-bc27-79ff8875eb17">|

**Comment by pierrepebay** [comment]
This was probably closed automatically with an other branch, reopening as it is still being adressed in #57
