### ISSUE TITLE
vt-tv: Improve CI

### ISSUE THREAD

**Issue by pierrepebay** [DARMA-tasking/vt-tv#32]
Replicate functionality and workflow of Magistrate CI.

- [ ] Add more tests
- [ ] Test API
- [ ] Test exported meshes
- [ ] Test the problematic configuration for #70 with a macOS runner

**Comment by ppebay** [comment]
We would also need to test cases such as `test-vt-tv.yaml`, or `ccm-example.yaml` below:

![Image](https://github.com/DARMA-tasking/vt-tv/assets/17439260/def0417d-7fde-4e3c-a9b3-c6038f8b8292)

to understand why some combinations of VTK (9.3) + vt-tv on Sonoma (14.3) output these problematic communication edges.

**Comment by ppebay** [comment]
> We would also need to test cases such as `test-vt-tv.yaml`, or `ccm-example.yaml` below:
> 
> ![Image](https://private-user-images.githubusercontent.com/17439260/343078263-def0417d-7fde-4e3c-a9b3-c6038f8b8292.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4ODA2NTAsIm5iZiI6MTcyMDg4MDM1MCwicGF0aCI6Ii8xNzQzOTI2MC8zNDMwNzgyNjMtZGVmMDQxN2QtN2ZkZS00ZTNjLWE5YjMtYzYwMzhmOGI4MjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDE0MTkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZTU2Y2RhZWQ4YjMyYjYyMTZjNjk1NGVkYWUxNThmNjBhYzEyYmRlYzBmM2JiYTc2NmRkOWMxMzhlMGMzNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LPMzHoQ4MpeTVhdPcK-NCLHuxdwMfdrngU0hG83RoEg)
> 
> to understand why some combinations of VTK (9.3) + vt-tv on Sonoma (14.3) output these problematic communication edges.

@tlamonthezie I would like to further elaborate on this, by means of linking this issue to #70, as it is now confirmed with VTK 9.3.**1** as well (the initial comment was with 9.3._0_
