### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by pierrepebay** [DARMA-tasking/vt-tv#39]
For now, it would need a description of how to use the standalone app with the (to be implemented) configuration file input.

Does NOT deploy documentation using Doxygen (that will be done in https://github.com/DARMA-tasking/vt-tv/issues/112)

**Comment by ppebay** [comment]
Isn't this subsumed into #112 @cwschilly @tlamonthezie

**Comment by tlamonthezie** [comment]
> Isn't this subsumed into

@ppp #112 is only about doxygen source code documentation. This one is more about usage, README.
I have updated the issue description as written in the PR #59 .
