### ISSUE TITLE
Identify parts of LBAF CI/CD that are relevant to LBAF-Viz and can be integrated into vt-tv

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/vt-tv#67]
This is issue is symmetrical of [LBAF #503](https://github.com/DARMA-tasking/LB-analysis-framework/issues/503)

**Comment by ppebay** [comment]
Revisiting this issue: in keeping with the deprecation of LBAF-Viz [LBAF #507](https://github.com/DARMA-tasking/LB-analysis-framework/issues/507), its attendant CI/CD will be deprecated as well.

**Comment by cwschilly** [comment]
See findings [here](https://github.com/DARMA-tasking/LB-analysis-framework/issues/503#issuecomment-2115681073)
