### ISSUE TITLE
Get build to work on MacOS

### ISSUE THREAD

**Issue by pierrepebay** [DARMA-tasking/vt-tv#68]
Building vt-tv on MacOS fails because of the usage of OpenMP. Setting appropriate flags and tests in the CMake system is needed.

**Comment by cwschilly** [comment]
@pierrepebay Is this fixed with [this commit](https://github.com/DARMA-tasking/vt-tv/pull/60/commits/0a66707e83fb5ffce5887994d755b3e46dee0b78)?

**Comment by pierrepebay** [comment]
@cwschilly yes it is, closing.
