### ISSUE TITLE
Add JSON validation

### ISSUE THREAD

**Issue by pierrepebay** [DARMA-tasking/vt-tv#7]
In order to validate the JSON data that is read in by the JSON reader, we will translate the approach used in LBAF into vt-tv.

2024 update:
1. vt-tv must be able to download the 2 scripts required for validation from the vt repository
- [JSON_data_files_validator.py](https://github.com/DARMA-tasking/vt/blob/develop/scripts/JSON_data_files_validator.py)
- [LBDatafile_schema.py](https://github.com/DARMA-tasking/vt/blob/develop/scripts/LBDatafile_schema.py)
2. Execute validation before running vt-tv and fire an error if not valid

**Comment by lifflander** [comment]
The JSON validator currently resides in the VT repository. We could fetch it here to check the file format: https://github.com/DARMA-tasking/vt/blob/develop/scripts/JSON_data_files_validator.py
